//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPCClient.SoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapService.SoapServiceSoap")]
    public interface SoapServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetGenerator", ReplyAction="*")]
        void ResetGenerator();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetGenerator", ReplyAction="*")]
        System.Threading.Tasks.Task ResetGeneratorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInteger", ReplyAction="*")]
        int GetInteger();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInteger", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetIntegerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetZero", ReplyAction="*")]
        int GetZero();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetZero", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetZeroAsync();
        
        // CODEGEN: Generating message contract since element name GetIntegersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIntegers", ReplyAction="*")]
        RPCClient.SoapService.GetIntegersResponse GetIntegers(RPCClient.SoapService.GetIntegersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIntegers", ReplyAction="*")]
        System.Threading.Tasks.Task<RPCClient.SoapService.GetIntegersResponse> GetIntegersAsync(RPCClient.SoapService.GetIntegersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIntegersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIntegers", Namespace="http://tempuri.org/", Order=0)]
        public RPCClient.SoapService.GetIntegersRequestBody Body;
        
        public GetIntegersRequest() {
        }
        
        public GetIntegersRequest(RPCClient.SoapService.GetIntegersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIntegersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint count;
        
        public GetIntegersRequestBody() {
        }
        
        public GetIntegersRequestBody(uint count) {
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIntegersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIntegersResponse", Namespace="http://tempuri.org/", Order=0)]
        public RPCClient.SoapService.GetIntegersResponseBody Body;
        
        public GetIntegersResponse() {
        }
        
        public GetIntegersResponse(RPCClient.SoapService.GetIntegersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIntegersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RPCClient.SoapService.ArrayOfInt GetIntegersResult;
        
        public GetIntegersResponseBody() {
        }
        
        public GetIntegersResponseBody(RPCClient.SoapService.ArrayOfInt GetIntegersResult) {
            this.GetIntegersResult = GetIntegersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoapServiceSoapChannel : RPCClient.SoapService.SoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapServiceSoapClient : System.ServiceModel.ClientBase<RPCClient.SoapService.SoapServiceSoap>, RPCClient.SoapService.SoapServiceSoap {
        
        public SoapServiceSoapClient() {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ResetGenerator() {
            base.Channel.ResetGenerator();
        }
        
        public System.Threading.Tasks.Task ResetGeneratorAsync() {
            return base.Channel.ResetGeneratorAsync();
        }
        
        public int GetInteger() {
            return base.Channel.GetInteger();
        }
        
        public System.Threading.Tasks.Task<int> GetIntegerAsync() {
            return base.Channel.GetIntegerAsync();
        }
        
        public int GetZero() {
            return base.Channel.GetZero();
        }
        
        public System.Threading.Tasks.Task<int> GetZeroAsync() {
            return base.Channel.GetZeroAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RPCClient.SoapService.GetIntegersResponse RPCClient.SoapService.SoapServiceSoap.GetIntegers(RPCClient.SoapService.GetIntegersRequest request) {
            return base.Channel.GetIntegers(request);
        }
        
        public RPCClient.SoapService.ArrayOfInt GetIntegers(uint count) {
            RPCClient.SoapService.GetIntegersRequest inValue = new RPCClient.SoapService.GetIntegersRequest();
            inValue.Body = new RPCClient.SoapService.GetIntegersRequestBody();
            inValue.Body.count = count;
            RPCClient.SoapService.GetIntegersResponse retVal = ((RPCClient.SoapService.SoapServiceSoap)(this)).GetIntegers(inValue);
            return retVal.Body.GetIntegersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RPCClient.SoapService.GetIntegersResponse> RPCClient.SoapService.SoapServiceSoap.GetIntegersAsync(RPCClient.SoapService.GetIntegersRequest request) {
            return base.Channel.GetIntegersAsync(request);
        }
        
        public System.Threading.Tasks.Task<RPCClient.SoapService.GetIntegersResponse> GetIntegersAsync(uint count) {
            RPCClient.SoapService.GetIntegersRequest inValue = new RPCClient.SoapService.GetIntegersRequest();
            inValue.Body = new RPCClient.SoapService.GetIntegersRequestBody();
            inValue.Body.count = count;
            return ((RPCClient.SoapService.SoapServiceSoap)(this)).GetIntegersAsync(inValue);
        }
    }
}
