//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPCClient.SoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapService.SoapServiceSoap")]
    public interface SoapServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SOAPResetGenerator", ReplyAction="*")]
        void SOAPResetGenerator();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SOAPResetGenerator", ReplyAction="*")]
        System.Threading.Tasks.Task SOAPResetGeneratorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SOAPGetInteger", ReplyAction="*")]
        int SOAPGetInteger();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SOAPGetInteger", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SOAPGetIntegerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SOAPGetZero", ReplyAction="*")]
        int SOAPGetZero();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SOAPGetZero", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SOAPGetZeroAsync();
        
        // CODEGEN: Generating message contract since element name SOAPGetIntegersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SOAPGetIntegers", ReplyAction="*")]
        RPCClient.SoapService.SOAPGetIntegersResponse SOAPGetIntegers(RPCClient.SoapService.SOAPGetIntegersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SOAPGetIntegers", ReplyAction="*")]
        System.Threading.Tasks.Task<RPCClient.SoapService.SOAPGetIntegersResponse> SOAPGetIntegersAsync(RPCClient.SoapService.SOAPGetIntegersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SOAPGetIntegersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SOAPGetIntegers", Namespace="http://tempuri.org/", Order=0)]
        public RPCClient.SoapService.SOAPGetIntegersRequestBody Body;
        
        public SOAPGetIntegersRequest() {
        }
        
        public SOAPGetIntegersRequest(RPCClient.SoapService.SOAPGetIntegersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SOAPGetIntegersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint count;
        
        public SOAPGetIntegersRequestBody() {
        }
        
        public SOAPGetIntegersRequestBody(uint count) {
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SOAPGetIntegersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SOAPGetIntegersResponse", Namespace="http://tempuri.org/", Order=0)]
        public RPCClient.SoapService.SOAPGetIntegersResponseBody Body;
        
        public SOAPGetIntegersResponse() {
        }
        
        public SOAPGetIntegersResponse(RPCClient.SoapService.SOAPGetIntegersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SOAPGetIntegersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RPCClient.SoapService.ArrayOfInt SOAPGetIntegersResult;
        
        public SOAPGetIntegersResponseBody() {
        }
        
        public SOAPGetIntegersResponseBody(RPCClient.SoapService.ArrayOfInt SOAPGetIntegersResult) {
            this.SOAPGetIntegersResult = SOAPGetIntegersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoapServiceSoapChannel : RPCClient.SoapService.SoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapServiceSoapClient : System.ServiceModel.ClientBase<RPCClient.SoapService.SoapServiceSoap>, RPCClient.SoapService.SoapServiceSoap {
        
        public SoapServiceSoapClient() {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SOAPResetGenerator() {
            base.Channel.SOAPResetGenerator();
        }
        
        public System.Threading.Tasks.Task SOAPResetGeneratorAsync() {
            return base.Channel.SOAPResetGeneratorAsync();
        }
        
        public int SOAPGetInteger() {
            return base.Channel.SOAPGetInteger();
        }
        
        public System.Threading.Tasks.Task<int> SOAPGetIntegerAsync() {
            return base.Channel.SOAPGetIntegerAsync();
        }
        
        public int SOAPGetZero() {
            return base.Channel.SOAPGetZero();
        }
        
        public System.Threading.Tasks.Task<int> SOAPGetZeroAsync() {
            return base.Channel.SOAPGetZeroAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RPCClient.SoapService.SOAPGetIntegersResponse RPCClient.SoapService.SoapServiceSoap.SOAPGetIntegers(RPCClient.SoapService.SOAPGetIntegersRequest request) {
            return base.Channel.SOAPGetIntegers(request);
        }
        
        public RPCClient.SoapService.ArrayOfInt SOAPGetIntegers(uint count) {
            RPCClient.SoapService.SOAPGetIntegersRequest inValue = new RPCClient.SoapService.SOAPGetIntegersRequest();
            inValue.Body = new RPCClient.SoapService.SOAPGetIntegersRequestBody();
            inValue.Body.count = count;
            RPCClient.SoapService.SOAPGetIntegersResponse retVal = ((RPCClient.SoapService.SoapServiceSoap)(this)).SOAPGetIntegers(inValue);
            return retVal.Body.SOAPGetIntegersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RPCClient.SoapService.SOAPGetIntegersResponse> RPCClient.SoapService.SoapServiceSoap.SOAPGetIntegersAsync(RPCClient.SoapService.SOAPGetIntegersRequest request) {
            return base.Channel.SOAPGetIntegersAsync(request);
        }
        
        public System.Threading.Tasks.Task<RPCClient.SoapService.SOAPGetIntegersResponse> SOAPGetIntegersAsync(uint count) {
            RPCClient.SoapService.SOAPGetIntegersRequest inValue = new RPCClient.SoapService.SOAPGetIntegersRequest();
            inValue.Body = new RPCClient.SoapService.SOAPGetIntegersRequestBody();
            inValue.Body.count = count;
            return ((RPCClient.SoapService.SoapServiceSoap)(this)).SOAPGetIntegersAsync(inValue);
        }
    }
}
