// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grpcservice {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEgtncnBjc2VydmljZSIGCgRWb2lkIhYKBVZhbHVl",
            "Eg0KBXZhbHVlGAEgASgFIhcKBlZhbHVlcxINCgV2YWx1ZRgBIAMoBTKyAQoL",
            "R1JQQ1NlcnZpY2USMgoHR2V0WmVybxIRLmdycGNzZXJ2aWNlLlZvaWQaEi5n",
            "cnBjc2VydmljZS5WYWx1ZSIAEjUKCkdldEludGVnZXISES5ncnBjc2Vydmlj",
            "ZS5Wb2lkGhIuZ3JwY3NlcnZpY2UuVmFsdWUiABI4CgtHZXRJbnRlZ2VycxIS",
            "LmdycGNzZXJ2aWNlLlZhbHVlGhMuZ3JwY3NlcnZpY2UuVmFsdWVzIgBiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedCodeInfo(null, new pbr::GeneratedCodeInfo[] {
            new pbr::GeneratedCodeInfo(typeof(global::Grpcservice.Void), global::Grpcservice.Void.Parser, null, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::Grpcservice.Value), global::Grpcservice.Value.Parser, new[]{ "Value_" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::Grpcservice.Values), global::Grpcservice.Values.Parser, new[]{ "Value" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Void : pb::IMessage<Void> {
    private static readonly pb::MessageParser<Void> _parser = new pb::MessageParser<Void>(() => new Void());
    public static pb::MessageParser<Void> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpcservice.ServiceReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Void() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Void(Void other) : this() {
    }

    public Void Clone() {
      return new Void(this);
    }

    public override bool Equals(object other) {
      return Equals(other as Void);
    }

    public bool Equals(Void other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
    }

    public int CalculateSize() {
      int size = 0;
      return size;
    }

    public void MergeFrom(Void other) {
      if (other == null) {
        return;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Value : pb::IMessage<Value> {
    private static readonly pb::MessageParser<Value> _parser = new pb::MessageParser<Value>(() => new Value());
    public static pb::MessageParser<Value> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpcservice.ServiceReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Value() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Value(Value other) : this() {
      value_ = other.value_;
    }

    public Value Clone() {
      return new Value(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int Value_FieldNumber = 1;
    private int value_;
    public int Value_ {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Value);
    }

    public bool Equals(Value other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Value_ != other.Value_) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Value_ != 0) hash ^= Value_.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Value_ != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Value_);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Value_ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value_);
      }
      return size;
    }

    public void MergeFrom(Value other) {
      if (other == null) {
        return;
      }
      if (other.Value_ != 0) {
        Value_ = other.Value_;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Value_ = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Values : pb::IMessage<Values> {
    private static readonly pb::MessageParser<Values> _parser = new pb::MessageParser<Values>(() => new Values());
    public static pb::MessageParser<Values> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpcservice.ServiceReflection.Descriptor.MessageTypes[2]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Values() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Values(Values other) : this() {
      value_ = other.value_.Clone();
    }

    public Values Clone() {
      return new Values(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_value_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> value_ = new pbc::RepeatedField<int>();
    public pbc::RepeatedField<int> Value {
      get { return value_; }
    }

    public override bool Equals(object other) {
      return Equals(other as Values);
    }

    public bool Equals(Values other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!value_.Equals(other.value_)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      hash ^= value_.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      value_.WriteTo(output, _repeated_value_codec);
    }

    public int CalculateSize() {
      int size = 0;
      size += value_.CalculateSize(_repeated_value_codec);
      return size;
    }

    public void MergeFrom(Values other) {
      if (other == null) {
        return;
      }
      value_.Add(other.value_);
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            value_.AddEntriesFrom(input, _repeated_value_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
