// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Grpcservice {
  public static class GRPCService
  {
    static readonly string __ServiceName = "grpcservice.GRPCService";

    static readonly Marshaller<global::Grpcservice.Void> __Marshaller_Void = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpcservice.Void.Parser.ParseFrom);
    static readonly Marshaller<global::Grpcservice.Value> __Marshaller_Value = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpcservice.Value.Parser.ParseFrom);
    static readonly Marshaller<global::Grpcservice.Values> __Marshaller_Values = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpcservice.Values.Parser.ParseFrom);

    static readonly Method<global::Grpcservice.Void, global::Grpcservice.Value> __Method_GetZero = new Method<global::Grpcservice.Void, global::Grpcservice.Value>(
        MethodType.Unary,
        __ServiceName,
        "GetZero",
        __Marshaller_Void,
        __Marshaller_Value);

    static readonly Method<global::Grpcservice.Void, global::Grpcservice.Value> __Method_GetInteger = new Method<global::Grpcservice.Void, global::Grpcservice.Value>(
        MethodType.Unary,
        __ServiceName,
        "GetInteger",
        __Marshaller_Void,
        __Marshaller_Value);

    static readonly Method<global::Grpcservice.Value, global::Grpcservice.Values> __Method_GetIntegers = new Method<global::Grpcservice.Value, global::Grpcservice.Values>(
        MethodType.Unary,
        __ServiceName,
        "GetIntegers",
        __Marshaller_Value,
        __Marshaller_Values);

    // service descriptor
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Grpcservice.ServiceReflection.Descriptor.Services[0]; }
    }

    // client interface
    public interface IGRPCServiceClient
    {
      global::Grpcservice.Value GetZero(global::Grpcservice.Void request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpcservice.Value GetZero(global::Grpcservice.Void request, CallOptions options);
      AsyncUnaryCall<global::Grpcservice.Value> GetZeroAsync(global::Grpcservice.Void request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpcservice.Value> GetZeroAsync(global::Grpcservice.Void request, CallOptions options);
      global::Grpcservice.Value GetInteger(global::Grpcservice.Void request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpcservice.Value GetInteger(global::Grpcservice.Void request, CallOptions options);
      AsyncUnaryCall<global::Grpcservice.Value> GetIntegerAsync(global::Grpcservice.Void request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpcservice.Value> GetIntegerAsync(global::Grpcservice.Void request, CallOptions options);
      global::Grpcservice.Values GetIntegers(global::Grpcservice.Value request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpcservice.Values GetIntegers(global::Grpcservice.Value request, CallOptions options);
      AsyncUnaryCall<global::Grpcservice.Values> GetIntegersAsync(global::Grpcservice.Value request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpcservice.Values> GetIntegersAsync(global::Grpcservice.Value request, CallOptions options);
    }

    // server-side interface
    public interface IGRPCService
    {
      Task<global::Grpcservice.Value> GetZero(global::Grpcservice.Void request, ServerCallContext context);
      Task<global::Grpcservice.Value> GetInteger(global::Grpcservice.Void request, ServerCallContext context);
      Task<global::Grpcservice.Values> GetIntegers(global::Grpcservice.Value request, ServerCallContext context);
    }

    // client stub
    public class GRPCServiceClient : ClientBase, IGRPCServiceClient
    {
      public GRPCServiceClient(Channel channel) : base(channel)
      {
      }
      public global::Grpcservice.Value GetZero(global::Grpcservice.Void request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_GetZero, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpcservice.Value GetZero(global::Grpcservice.Void request, CallOptions options)
      {
        var call = CreateCall(__Method_GetZero, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpcservice.Value> GetZeroAsync(global::Grpcservice.Void request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_GetZero, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpcservice.Value> GetZeroAsync(global::Grpcservice.Void request, CallOptions options)
      {
        var call = CreateCall(__Method_GetZero, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Grpcservice.Value GetInteger(global::Grpcservice.Void request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_GetInteger, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpcservice.Value GetInteger(global::Grpcservice.Void request, CallOptions options)
      {
        var call = CreateCall(__Method_GetInteger, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpcservice.Value> GetIntegerAsync(global::Grpcservice.Void request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_GetInteger, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpcservice.Value> GetIntegerAsync(global::Grpcservice.Void request, CallOptions options)
      {
        var call = CreateCall(__Method_GetInteger, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Grpcservice.Values GetIntegers(global::Grpcservice.Value request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_GetIntegers, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpcservice.Values GetIntegers(global::Grpcservice.Value request, CallOptions options)
      {
        var call = CreateCall(__Method_GetIntegers, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpcservice.Values> GetIntegersAsync(global::Grpcservice.Value request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_GetIntegers, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpcservice.Values> GetIntegersAsync(global::Grpcservice.Value request, CallOptions options)
      {
        var call = CreateCall(__Method_GetIntegers, options);
        return Calls.AsyncUnaryCall(call, request);
      }
    }

    // creates service definition that can be registered with a server
    public static ServerServiceDefinition BindService(IGRPCService serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder(__ServiceName)
          .AddMethod(__Method_GetZero, serviceImpl.GetZero)
          .AddMethod(__Method_GetInteger, serviceImpl.GetInteger)
          .AddMethod(__Method_GetIntegers, serviceImpl.GetIntegers).Build();
    }

    // creates a new client
    public static GRPCServiceClient NewClient(Channel channel)
    {
      return new GRPCServiceClient(channel);
    }

  }
}
#endregion
